micronaut:
  application:
    name: relatorioService
  server:
    port: 8082
mongodb:
  url: 'mongodb//localhost:27017/vendas'
netty:
  default:
    allocator:
      max-order: 3
kafka:
  booststrap:
    servers: localhost:9092
